# Generated by Django 4.0.5 on 2022-06-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meta',
            field=models.TextField(blank=True, null=True, verbose_name='Meta-data about the user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.TextField(blank=True, null=True, verbose_name='User preferences'),
        ),
    ]
